name: deploy-backend

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"
    # pull_request:
    # - main

env:
  PROJECT_LOCATION: backend/API/API.csproj
  ELASTIC_BEANSTALK_NAME: ${{ secrets.AWS_BEANSTALK_APPLICATION_NAME }}
  ELASTIC_BEANSTALK_ENV_NAME: ${{ secrets.AWS_BEANSTALK_ENV_NAME }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore $PROJECT_LOCATION
      - name: Build
        run: dotnet build --no-restore $PROJECT_LOCATION
      - name: Pack
        run: |
          dotnet publish $PROJECT_LOCATION -c Release --self-contained --runtime linux-x64 --output "${{ github.workspace }}/${{github.run_id}}"
          cd ${{github.run_id}}
          zip -r ../${{github.run_id}}.zip .
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4.3.3
        with:
          name: deploy-files
          path: ${{ github.run_id }}.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/download-artifact@v4.1.7
        #with:
        #name: deploy-files

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-north-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Deploy
        run: |
          aws s3 cp "deploy-files/${{github.run_id}}.zip" s3://elasticbeanstalk-eu-north-1-${{ secrets.AWS_ACCOUNT_ID }}/artifact/Bug-Tracker/
          aws elasticbeanstalk create-application-version --application-name $ELASTIC_BEANSTALK_NAME --version-label ${{github.run_id}} --description ${{github.run_id}} --source-bundle S3Bucket="elasticbeanstalk-eu-north-1-${{ secrets.AWS_ACCOUNT_ID }}",S3Key="artifact/Bug-Tracker/${{github.run_id}}.zip"
          aws elasticbeanstalk update-environment --application-name $ELASTIC_BEANSTALK_NAME --environment-name $ELASTIC_BEANSTALK_ENV_NAME --version-label ${{github.run_id}}
          aws elasticbeanstalk wait environment-updated --application-name $ELASTIC_BEANSTALK_NAME --environment-name $ELASTIC_BEANSTALK_ENV_NAME
