name: deploy-backend

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"
    # pull_request:
    # - main

env:
  PROJECT_LOCATION: backend/API/API.csproj
  ELASTIC_BEANSTALK_NAME: ${{ secrets.AWS_BEANSTALK_APPLICATION_NAME }}
  ELASTIC_BEANSTALK_ENV_NAME: ${{ secrets.AWS_BEANSTALK_ENV_NAME }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 7.0.x
      - name: Restore dependencies
        run: dotnet restore $PROJECT_LOCATION
      - name: Build
        run: dotnet build --no-restore $PROJECT_LOCATION
      - name: Pack
        run: |
          dotnet publish $PROJECT_LOCATION -c Release --output "${{ github.workspace }}/${{github.run_id}}"
          cd ${{github.run_id}}
          zip -r ../${{github.run_id}}.zip .
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4.3.3
        with:
          name: deploy-files
          path: ${{ github.run_id }}.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/download-artifact@v4.1.7
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: eu-north-1
